"""Write a Sphinx project from generated pages and diagrams, and build it."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

from .outline import Page

# Diagrams are pre-rendered to static SVG by render.py and embedded as plain images,
# so the Sphinx build needs no drawio extension (and therefore no Xvfb/Chromium at
# build time) regardless of which diagram backend produced them.
_CONF_PY = '''\
# Sphinx configuration generated by secagent.
project = {project!r}
author = "secagent"
extensions = ["myst_parser"]
html_theme = "furo"
html_static_path = ["_static"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
templates_path = []
source_suffix = {{".rst": "restructuredtext", ".md": "markdown"}}
'''

_INDEX_HEADER = """\
{title}
{underline}

Generated by **secagent** — a deep-dive of the codebase built from project structure,
file summaries, and the inter-component IO map.

.. toctree::
   :maxdepth: 2
   :caption: Contents

"""


def write_project(
    out_dir: Path,
    project_name: str,
    pages: list[Page],
    diagram_sources: dict[str, str],
    banner: str = "",
) -> dict:
    """Write conf.py, index.rst, pages, and the editable ``.drawio`` sources.

    Diagram images (``.svg``) are produced separately by :func:`render.render_diagrams`
    into the same ``_diagrams`` directory; this only writes the editable sources.
    """
    src = out_dir / "source"
    diagrams_dir = src / "_diagrams"
    static_dir = src / "_static"
    for d in (src, diagrams_dir, static_dir):
        d.mkdir(parents=True, exist_ok=True)

    conf = _CONF_PY.format(project=project_name)
    if banner:
        # CUI marking (CMMC-6): a furo announcement banner on every page plus a
        # marking footer appended to every document via rst_epilog.
        epilog = f"\n\n----\n\n**{banner}**\n"
        conf += (
            f"\nhtml_theme_options = {{'announcement': {banner!r}}}\n"
            f"rst_epilog = {epilog!r}\n"
        )
    (src / "conf.py").write_text(conf, encoding="utf-8")

    # Editable .drawio sources (offered as downloads beside the rendered images).
    for fname, xml in diagram_sources.items():
        (diagrams_dir / fname).write_text(xml, encoding="utf-8")

    # Pages.
    for page in pages:
        header = f"{page.title}\n{'=' * len(page.title)}\n\n"
        (src / page.filename).write_text(header + page.body + "\n", encoding="utf-8")

    # index.rst with a toctree of all pages.
    title = f"{project_name} documentation"
    index = _INDEX_HEADER.format(title=title, underline="=" * len(title))
    index += "".join(f"   {p.filename.rsplit('.', 1)[0]}\n" for p in pages)
    (src / "index.rst").write_text(index, encoding="utf-8")

    return {
        "source_dir": str(src),
        "diagrams_dir": str(diagrams_dir),
        "pages": [p.filename for p in pages],
        "diagrams": list(diagram_sources),
    }


def run_sphinx_build(out_dir: Path) -> dict:
    """Invoke ``sphinx-build`` to produce HTML. Returns a report (never raises)."""
    src = out_dir / "source"
    build = out_dir / "build" / "html"
    build.mkdir(parents=True, exist_ok=True)
    cmd = [sys.executable, "-m", "sphinx", "-b", "html", "-q", str(src), str(build)]
    try:
        proc = subprocess.run(cmd, capture_output=True, text=True, check=False)  # noqa: S603
    except (subprocess.SubprocessError, OSError) as exc:
        return {"ok": False, "error": str(exc), "html_dir": str(build)}
    return {
        "ok": proc.returncode == 0,
        "returncode": proc.returncode,
        "html_dir": str(build),
        "index_html": str(build / "index.html"),
        "stderr_tail": proc.stderr[-800:] if proc.stderr else "",
    }
