"""Tests for `secagent.output`: the shared `Coverage` / `Provenance` primitives.

This repo has shipped a fake or self-inconsistent coverage block five separate
times under five different names (a scanner that silently truncated files, a
testgen that dropped unreadable files, a docs build that rendered 9 of 17
modules, an analyze pass that reported `tus_skipped: 0` for files never in the
compile database). The point of `Coverage` is that its own numbers cannot be
inconsistent with each other, and these tests exist to prove that every rule
that makes that true actually rejects the input it claims to reject — and,
just as importantly, that it does not reject the honest neighbouring case.
"""

from __future__ import annotations

import itertools
import json
from datetime import UTC, datetime

import pytest

from secagent.output import STATES, Coverage, Provenance, UnitState, coverage_to_dict

# Keeping the exhaustive sweep small (0..3 per count) makes the invariant test a
# genuine property test over hundreds of concrete cases while still running in
# well under a second — the point is coverage of the *shape* of the invariant
# (every combination of zero/nonzero/equal/unequal states), not the specific
# magnitudes.
_SMALL = range(4)


def _valid(succeeded: int, partial: int, failed: int, skipped: int) -> Coverage:
    """Build the unique valid `Coverage` for one (succeeded, partial, failed, skipped)."""
    attempted = succeeded + partial + failed
    eligible = attempted + skipped
    return Coverage(
        eligible=eligible,
        attempted=attempted,
        succeeded=succeeded,
        partial=partial,
        failed=failed,
        skipped=skipped,
    )


# --------------------------------------------------------------------------
# The core invariant, exhaustively over small counts.
# --------------------------------------------------------------------------


def test_invariant_holds_and_complete_is_exact_over_all_small_combinations():
    """For every (succeeded, partial, failed, skipped) in range(4)**4, the derived
    Coverage must construct, and `complete` must match its definition exactly.

    This is the property test called for by the task: hundreds of concrete cases
    generated by itertools.product rather than three hand-picked examples, so it
    covers combinations (e.g. succeeded=0 and partial=0 and failed=0 and skipped=0,
    or eligible=0) that hand-picked examples tend to skip.
    """
    for s, p, f, k in itertools.product(_SMALL, repeat=4):
        cov = _valid(s, p, f, k)
        expected_complete = (cov.attempted == cov.eligible) and p == 0 and f == 0
        assert cov.complete == expected_complete, (s, p, f, k)


def test_perturbing_any_single_count_by_one_breaks_the_invariant():
    """Every field of a valid Coverage is load-bearing: nudging exactly one of the
    six numeric fields by +-1, holding the rest fixed, must always raise.

    This is the mechanism-level version of "the numbers must add up" — it isn't
    enough that some inconsistent inputs raise, EVERY single-field perturbation
    away from a valid point must raise, or the invariant has a blind spot.
    """
    checked = 0
    for s, p, f, k in itertools.product(_SMALL, repeat=4):
        attempted = s + p + f
        eligible = attempted + k
        base = {"eligible": eligible, "attempted": attempted, "succeeded": s,
                "partial": p, "failed": f, "skipped": k}
        for field_name in base:
            for delta in (1, -1):
                bad = dict(base)
                bad[field_name] = base[field_name] + delta
                with pytest.raises(ValueError):
                    Coverage(**bad)
                checked += 1
    assert checked == (4**4) * 6 * 2


def test_complete_is_false_whenever_eligible_is_none_for_every_combination():
    """`complete` must never be inferred when the population is unknowable.

    `secagent analyze ingest` reads findings from an external SARIF report and has
    no way to see the translation-unit population, so `eligible=None`. Guards
    against a plausible-looking regression: "if attempted > 0 and failed == 0
    and partial == 0, call it complete" would accidentally treat an unknowable
    population as fully covered.
    """
    for s, p, f, k in itertools.product(_SMALL, repeat=4):
        attempted = s + p + f
        cov = Coverage(eligible=None, attempted=attempted, succeeded=s,
                        partial=p, failed=f, skipped=k)
        assert cov.complete is False, (s, p, f, k)


# --------------------------------------------------------------------------
# Individual validation rules: a rejection test paired with a silence test.
# --------------------------------------------------------------------------


def test_negative_count_rejected():
    """Rule 1: every count must be >= 0. A negative count cannot arise from any
    real tally of units and signals a producer that built the numbers by hand.

    NOTE on isolation: a negative succeeded/partial/failed/skipped can never be
    isolated from rule 5 by choice of input alone. Rule 5 loops over all four
    STATES unconditionally and compares a tally that is always >= 0 (why_counts)
    against the reported count — so whenever a reported count is negative, "0 (or
    more) > negative" is true no matter what `why` contains, and rule 5 fires
    too. Mutation-tested this directly: with rule 1's own check deleted, this
    exact input still raises ValueError, just from rule 5's branch instead ("why
    cannot name more units..."). The `match` below is rule 1's own distinctive
    wording, so the test still correctly fails (wrong message) when rule 1 is
    the one removed, even though *some* ValueError survives either way.
    """
    with pytest.raises(ValueError, match="must be >= 0, got -1"):
        Coverage(eligible=0, attempted=0, succeeded=-1, partial=0, failed=1, skipped=0)


def test_zero_counts_are_accepted():
    """Silence test for rule 1: an all-zero Coverage (a domain with no eligible
    units at all, e.g. `docs` diagrams on a repo with none) is legitimate and
    must not be rejected by the >= 0 check.
    """
    cov = Coverage(eligible=0, attempted=0, succeeded=0, partial=0, failed=0, skipped=0)
    assert cov.complete is True


def test_negative_eligible_rejected():
    """Rule 1 (eligible variant): `eligible` is `int | None`, and when it IS an
    int it must still be >= 0 — `None` is the only legal way to say "unknown".

    NOTE on isolation: like the plain negative-count case, this cannot be
    isolated from rule 3 by choice of input — rule 1's own check keeps
    `attempted`/`skipped` non-negative, so `attempted + skipped` can never equal
    a negative `eligible`, and rule 3 necessarily also fires. Mutation-tested:
    with rule 1's eligible check deleted, this input still raises, via rule 3's
    "does not equal attempted(...)" message. The distinctive `match` below is
    what actually distinguishes "rule 1 fired" from "rule 3 fired instead".
    """
    with pytest.raises(ValueError, match="must be None or >= 0"):
        Coverage(eligible=-1, attempted=0, succeeded=0, partial=0, failed=0, skipped=0)


def test_none_eligible_is_accepted_without_reconciliation():
    """Silence test: `eligible=None` (population genuinely unknowable, e.g.
    `analyze ingest` from an external SARIF report) must construct cleanly and
    skip the eligible == attempted + skipped reconciliation entirely.
    """
    cov = Coverage(eligible=None, attempted=3, succeeded=2, partial=0, failed=1, skipped=100)
    assert cov.eligible is None
    assert cov.complete is False


def test_attempted_not_matching_sum_rejected():
    """Rule 2: `attempted` must equal succeeded + partial + failed. This is
    exactly the bug where a report's own files_analyzed/files_failed/files_partial
    trio could disagree with each other because nothing forced them to reconcile.
    """
    with pytest.raises(ValueError, match="does not equal succeeded"):
        Coverage(eligible=10, attempted=8, succeeded=5, partial=1, failed=1, skipped=2)


def test_attempted_matching_sum_is_accepted():
    """Silence test for rule 2: the honest neighbouring case (attempted correctly
    equal to the sum of the three outcome counts) must not be rejected.
    """
    cov = Coverage(eligible=10, attempted=7, succeeded=5, partial=1, failed=1, skipped=3)
    assert cov.attempted == 7


def test_eligible_not_matching_attempted_plus_skipped_rejected():
    """Rule 3: when eligible is known, eligible must equal attempted + skipped.
    This is the "files_skipped_by_cap derived from selection, files_analyzed
    derived from what ran, and nothing reconciled the two" defect, generalised.
    """
    with pytest.raises(ValueError, match="does not equal attempted"):
        Coverage(eligible=11, attempted=8, succeeded=6, partial=1, failed=1, skipped=2)


def test_eligible_matching_attempted_plus_skipped_is_accepted():
    """Silence test for rule 3: eligible correctly reconciled with attempted +
    skipped must construct without complaint."""
    cov = Coverage(eligible=10, attempted=8, succeeded=6, partial=1, failed=1, skipped=2)
    assert cov.eligible == 10


def test_why_state_outside_states_rejected():
    """Rule 4a: every `why` entry's state must be one of the four STATES. A typo
    like "sucess" or a stray "attempted" (which is not a state — see module
    docstring) must not silently pass through into a report artifact.
    """
    with pytest.raises(ValueError, match="is not one of"):
        Coverage(eligible=1, attempted=1, succeeded=1, partial=0, failed=0, skipped=0,
                 why={"a.c": UnitState(state="attempted", reason="bogus")})


def test_why_state_in_states_is_accepted():
    """Silence test for rule 4a: a `why` entry using one of the four real
    STATES values must be accepted."""
    cov = Coverage(eligible=1, attempted=0, succeeded=0, partial=0, failed=0, skipped=1,
                    why={"a.c": UnitState(state="skipped", reason="scan.max_files=0")})
    assert cov.why["a.c"].state == "skipped"


def test_why_blank_reason_rejected():
    """Rule 4b: a `why` entry's reason must be non-empty after stripping
    whitespace. A reason of "" or "   " names no cause at all and is exactly the
    "skipped: 0" style placeholder this module exists to make impossible.
    """
    with pytest.raises(ValueError, match="empty reason"):
        Coverage(eligible=1, attempted=0, succeeded=0, partial=0, failed=0, skipped=1,
                 why={"a.c": UnitState(state="skipped", reason="   ")})


def test_why_nonblank_reason_is_accepted():
    """Silence test for rule 4b: a real, non-empty reason must not be rejected."""
    cov = Coverage(eligible=1, attempted=0, succeeded=0, partial=0, failed=0, skipped=1,
                    why={"a.c": UnitState(state="skipped", reason="scan.max_files=0")})
    assert cov.why["a.c"].reason == "scan.max_files=0"


def test_why_names_more_failures_than_failed_count_rejected():
    """Rule 5, explicitly required by the task: naming three failed units in
    `why` while reporting failed=1 means the headline count understates the
    detail map sitting right next to it — the detail is presumably the true one.

    eligible/attempted/succeeded/partial/failed/skipped here are deliberately
    chosen to individually satisfy rules 1-3 (attempted == sum of outcomes,
    eligible == attempted + skipped) so that this test isolates rule 5 rather
    than incidentally tripping over the attempted/eligible reconciliation
    first — three "failed" `why` entries against a reported `failed=1`, with
    everything else self-consistent.
    """
    why = {
        "a.c": UnitState(state="failed", reason="parse error"),
        "b.c": UnitState(state="failed", reason="timeout"),
        "c.c": UnitState(state="failed", reason="OOM"),
    }
    with pytest.raises(ValueError, match="why cannot name more"):
        Coverage(eligible=1, attempted=1, succeeded=0, partial=0, failed=1, skipped=0, why=why)


def test_why_count_matching_reported_count_is_accepted():
    """Silence test for rule 5: naming exactly as many failed units in `why` as
    the `failed` count reports must be accepted, not just "fewer than"."""
    why = {
        "a.c": UnitState(state="failed", reason="parse error"),
        "b.c": UnitState(state="failed", reason="timeout"),
    }
    cov = Coverage(eligible=2, attempted=2, succeeded=0, partial=0, failed=2, skipped=0, why=why)
    assert cov.failed == 2


# --------------------------------------------------------------------------
# from_why
# --------------------------------------------------------------------------

_WHY_FIXTURES = [
    {},
    {"a.c": UnitState(state="succeeded", reason="ok")},
    {
        "a.c": UnitState(state="succeeded", reason="ok"),
        "b.c": UnitState(state="failed", reason="parse error"),
        "c.c": UnitState(state="skipped", reason="scan.max_files=2"),
    },
    {
        f"file{i}.c": UnitState(
            state=STATES[i % len(STATES)], reason=f"reason {i}"
        )
        for i in range(12)
    },
]


@pytest.mark.parametrize("why", _WHY_FIXTURES)
def test_from_why_derives_a_valid_coverage(why):
    """`from_why` is the anti-fabrication constructor: counts are tallied FROM
    `why`, so they cannot independently drift from it the way hand-typed
    integers could. Constructing over several generated `why` maps (including
    the empty one) proves the derivation itself always satisfies the invariant
    `Coverage.__post_init__` enforces.
    """
    cov = Coverage.from_why(why)
    assert cov.attempted == cov.succeeded + cov.partial + cov.failed
    assert cov.eligible == cov.attempted + cov.skipped
    for state in STATES:
        expected = sum(1 for u in why.values() if u.state == state)
        assert getattr(cov, state) == expected


def test_from_why_eligible_omitted_means_why_is_the_whole_population():
    """Omitting `eligible` derives it as len(why) — appropriate for a producer
    like scan that enumerates every eligible unit's outcome in `why`."""
    why = {
        "a.c": UnitState(state="succeeded", reason="ok"),
        "b.c": UnitState(state="skipped", reason="scan.max_files=1"),
    }
    cov = Coverage.from_why(why)
    assert cov.eligible == 2
    assert cov.complete is False  # b.c was skipped


def test_from_why_explicit_eligible_none_stays_unknowable():
    """Passing `eligible=None` explicitly must be preserved as None, distinct
    from the omitted-default case above — the two are NOT the same call, and a
    private sentinel (not None as the default) is what keeps them distinguishable.
    """
    why = {"a.c": UnitState(state="succeeded", reason="ok")}
    cov = Coverage.from_why(why, eligible=None)
    assert cov.eligible is None
    assert cov.complete is False


def test_from_why_omitted_and_explicit_none_differ():
    """Direct comparison of the two `from_why` call shapes on the same `why`,
    proving they really do produce different, both-correct results."""
    why = {"a.c": UnitState(state="succeeded", reason="ok")}
    omitted = Coverage.from_why(why)
    explicit_none = Coverage.from_why(why, eligible=None)
    assert omitted.eligible == 1
    assert explicit_none.eligible is None


def test_from_why_explicit_eligible_matching_len_why_is_accepted():
    """Passing an explicit int `eligible` that happens to equal `len(why)` (the
    same value the omitted-default case would compute) is redundant but valid —
    from_why does not special-case "was eligible passed at all" beyond the
    None-vs-omitted distinction."""
    why = {"a.c": UnitState(state="failed", reason="parse error")}
    cov = Coverage.from_why(why, eligible=1)
    assert cov.eligible == 1


def test_from_why_explicit_eligible_disagreeing_with_why_is_rejected():
    """from_why does NOT let a caller override eligible to a number the `why`
    tally cannot support: since attempted + skipped always equals len(why) for
    tallied counts, an eligible that names a bigger (or smaller) population than
    `why` actually accounts for still fails the same reconciliation check a
    hand-built Coverage would — from_why derives, it does not launder a wrong
    number past validation.
    """
    why = {"a.c": UnitState(state="failed", reason="parse error")}
    with pytest.raises(ValueError, match="does not equal attempted"):
        Coverage.from_why(why, eligible=5)


# --------------------------------------------------------------------------
# to_dict
# --------------------------------------------------------------------------


def test_to_dict_include_why_false_omits_why_keeps_counts_and_complete():
    """The dict a command RETURNS (printed to CLI stdout, forwarded verbatim by
    the pi extension into a model's context) must stay bounded regardless of
    how many units a run touched — `include_why=False` is how callers get that.
    """
    why = {"a.c": UnitState(state="failed", reason="parse error")}
    cov = Coverage(eligible=2, attempted=1, succeeded=0, partial=0, failed=1, skipped=1, why=why)
    d = cov.to_dict(include_why=False)
    assert "why" not in d
    assert d["eligible"] == 2
    assert d["attempted"] == 1
    assert d["succeeded"] == 0
    assert d["partial"] == 0
    assert d["failed"] == 1
    assert d["skipped"] == 1
    assert d["complete"] is False


def test_to_dict_default_includes_why_and_round_trips_through_json():
    """The full block (with `why`) goes into the JSON artifact on disk, so
    `to_dict()` must actually be JSON-serialisable end to end, not merely
    dict-shaped — a non-serialisable value here would only surface at write time
    on a real run.
    """
    why = {"a.c": UnitState(state="succeeded", reason="ok")}
    cov = Coverage(eligible=1, attempted=1, succeeded=1, partial=0, failed=0, skipped=0, why=why)
    d = cov.to_dict()
    assert d["why"] == {"a.c": {"state": "succeeded", "reason": "ok"}}
    round_tripped = json.loads(json.dumps(d))
    assert round_tripped == d


def test_coverage_to_dict_renders_multiple_domains():
    """A command with two populations (e.g. `analyze scan`'s translation-unit
    coverage and finding-triage coverage) emits two domains under `coverage`,
    not one merged/averaged block — this is the helper that renders that shape.
    """
    domains = {
        "files": Coverage(eligible=2, attempted=2, succeeded=2, partial=0, failed=0, skipped=0),
        "triage": Coverage(eligible=5, attempted=3, succeeded=2, partial=0, failed=1, skipped=2),
    }
    out = coverage_to_dict(domains, include_why=False)
    assert set(out) == {"files", "triage"}
    assert out["files"]["complete"] is True
    assert out["triage"]["complete"] is False
    assert "why" not in out["files"]


# --------------------------------------------------------------------------
# Silence: the fully successful, unbounded run.
# --------------------------------------------------------------------------


def test_fully_successful_unbounded_run_is_valid_and_complete():
    """The baseline honest case: eligible == attempted == succeeded, zero
    partial/failed/skipped, empty why. Must construct and report complete=True —
    if THIS is ever rejected, the validator is rejecting everything, which is as
    useless as rejecting nothing.
    """
    cov = Coverage(eligible=4, attempted=4, succeeded=4, partial=0, failed=0, skipped=0)
    assert cov.complete is True
    assert cov.to_dict(include_why=False)["complete"] is True


# --------------------------------------------------------------------------
# Provenance
# --------------------------------------------------------------------------


def test_provenance_rejects_bare_string_model():
    """A bare `str` for `model` must be rejected by its OWN dedicated check:
    `for m in "gemma"` silently iterates characters, not model names, and
    something downstream doing exactly that is the concrete bug this guards
    against — the dedicated check exists specifically to name that failure mode
    in the error message, rather than relying on the generic "must be a list"
    check that would also catch a bare string as a side effect (a str is not a
    list either). `match` targets wording unique to the dedicated check so the
    test fails (mismatched message) if that check — rather than the generic
    one — is what gets deleted.
    """
    with pytest.raises(ValueError, match="iterating it yields individual characters"):
        Provenance(secagent_version="0.1.0", model="gemma", endpoint="http://x",
                   generated_at="2026-01-01T00:00:00Z", heuristic_only=False)


def test_provenance_accepts_list_of_models():
    """Silence test: the correct shape (a list of model name strings) must be
    accepted, including the multi-model case a docs run or a triaged analyze
    run actually produces (index-time model + render-time model, or a
    no-model producer alongside a triage model).
    """
    prov = Provenance(secagent_version="0.1.0", model=["gemma3:27b", "ikos"],
                       endpoint="http://x", generated_at="2026-01-01T00:00:00Z",
                       heuristic_only=False)
    assert prov.model == ["gemma3:27b", "ikos"]


def test_provenance_rejects_empty_string_in_model_list():
    """A list containing a blank/whitespace-only entry names no real model and
    is the same "placeholder that looks like an answer" failure mode as an
    empty `why` reason."""
    with pytest.raises(ValueError, match="list of non-empty strings"):
        Provenance(secagent_version="0.1.0", model=["gemma3:27b", "  "],
                   endpoint="http://x", generated_at="2026-01-01T00:00:00Z",
                   heuristic_only=False)


def test_provenance_rejects_heuristic_only_with_named_model():
    """`heuristic_only=True` together with a non-empty `model` is contradictory:
    a heuristic-fallback result was, by definition, not produced by any of the
    named models. Two evaluation agents each wasted a run unable to tell a
    working model from a broken endpoint from the heuristic fallback — this
    keeps the two signals from disagreeing with each other.
    """
    with pytest.raises(ValueError, match="is contradictory with a non-empty"):
        Provenance(secagent_version="0.1.0", model=["gemma3:27b"], endpoint="http://x",
                   generated_at="2026-01-01T00:00:00Z", heuristic_only=True)


def test_provenance_heuristic_only_with_empty_model_is_accepted():
    """Silence test: the actually-consistent heuristic-fallback shape
    (heuristic_only=True, model=[]) must not be rejected."""
    prov = Provenance(secagent_version="0.1.0", model=[], endpoint="http://x",
                       generated_at="2026-01-01T00:00:00Z", heuristic_only=True)
    assert prov.heuristic_only is True
    assert prov.model == []


def test_provenance_rejects_non_z_suffixed_timestamp():
    """`generated_at` must be UTC and say so unambiguously via a 'Z' suffix — a
    naive or offset timestamp without it leaves a reader guessing the timezone
    of every other timestamp in the same report.

    NOTE on isolation: this cannot be isolated from the fromisoformat guard
    below by choice of input either — with the Z-suffix check deleted, this
    exact offset-suffixed string reaches `self.generated_at[:-1] + "+00:00"`,
    which mangles the offset into something `fromisoformat` also rejects, so
    the guard fires anyway. Mutation-tested this directly. The distinctive
    `match` (this check's own wording, "ending in 'Z'") is what actually
    distinguishes the two — the fromisoformat guard's message says "is not a
    valid ISO-8601 timestamp" instead, which does not match.
    """
    with pytest.raises(ValueError, match="ending in 'Z'"):
        Provenance(secagent_version="0.1.0", model=[], endpoint="http://x",
                   generated_at="2026-01-01T00:00:00+02:00", heuristic_only=False)


def test_provenance_rejects_malformed_timestamp_despite_z_suffix():
    """The `fromisoformat` guard is a distinct check from the Z-suffix check: a
    string can satisfy "ends with Z" while still not being a real timestamp
    (e.g. an invalid month), and this exercises that branch specifically —
    the same mechanism that would let a hand-typed `generated_at` with a typo
    through if only the suffix were checked.
    """
    with pytest.raises(ValueError, match="is not a valid ISO-8601 timestamp"):
        Provenance(secagent_version="0.1.0", model=[], endpoint="http://x",
                   generated_at="2026-13-45T99:99:99Z", heuristic_only=False)


def test_provenance_now_produces_a_z_suffixed_timestamp_that_actually_parses():
    """`Provenance.now()` must produce a timestamp that both ends in 'Z' AND
    round-trips through real ISO-8601 parsing — `datetime.fromisoformat` does
    not accept a bare 'Z' suffix directly, so the test exercises the same
    normalisation a real consumer would need, rather than just checking
    `.endswith("Z")` and assuming the rest is well-formed.
    """
    prov = Provenance.now(model=["gemma3:27b"], endpoint="http://x")
    assert prov.generated_at.endswith("Z")
    parsed = datetime.fromisoformat(prov.generated_at[:-1] + "+00:00")
    assert parsed.tzinfo is not None
    now = datetime.now(UTC)
    assert abs((now - parsed).total_seconds()) < 60
    assert prov.secagent_version  # pulled from secagent.__version__, not invented


def test_provenance_to_dict_round_trips_through_json():
    """`Provenance.to_dict()` is written into report JSON alongside `coverage`,
    so it must be plain-JSON-serialisable, including the `model` list."""
    prov = Provenance.now(model=["gemma3:27b", "ikos"], endpoint="http://x",
                           heuristic_only=False)
    d = prov.to_dict()
    round_tripped = json.loads(json.dumps(d))
    assert round_tripped == d
    assert round_tripped["model"] == ["gemma3:27b", "ikos"]
