"""UC100 orchestration: produce and post merge-request reviews and replies.

The review is generated by a single budgeted LLM call (deterministic, low-temperature)
rather than a long tool loop: the affordance engine has already distilled the
project, so the model receives a compact, high-signal prompt — MR metadata, the
relevant affordances for the changed files, and a budgeted diff.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

from ... import gitscope
from ...affordances import grounding
from ...affordances.api import index_repo
from ...affordances.retrieval import ContextBuilder
from ...affordances.store import AffordanceStore
from ...audit import get_audit_logger
from ...config import Settings
from ...llm.client import LLMClient
from ...llm.tokenizer import TokenCounter
from ...mcp.gitlab_harness import GitLabClient
from ...sanitize import harden_system_prompt, wrap_untrusted
from .persona import Persona, load_persona

log = logging.getLogger(__name__)

_SIGNATURE = "\n\n---\n*Reviewed by secagent ({persona}) — a local-model agent.*"


def _apply_marking(banner: str, body: str) -> str:
    """Prepend/append a CUI marking banner to a comment body (CMMC-6)."""
    if not banner:
        return body
    return f"**{banner}**\n\n{body}\n\n**{banner}**"


def _review_body(
    settings: Settings,
    persona: Persona,
    *,
    meta: dict[str, Any],
    changes: dict[str, Any],
    repo: str | Path | None,
    llm: LLMClient,
) -> tuple[str, list[str], grounding.Grounding | None]:
    """The shared review-generation core: full-repo affordance grounding, a
    diff-budgeted prompt, one LLM call, then grounding + marking + signature.

    Both `review_merge_request` (a GitLab merge request) and `review_local_changes`
    (a local `gitscope.ChangeSet`) call this with the identical
    ``{"changes": [{"new_path", "old_path", "diff"}, ...]}`` shape — see
    `gitscope.ChangeSet.to_gitlab_style` — so neither forks the engine; only how
    ``meta``/``changes`` are gathered, and what happens to the result afterward
    (post to GitLab vs. print to stdout), differs between the two callers.

    ``meta`` supplies the prompt's framing fields (``title``/``description``/
    ``source_branch``/``target_branch``) — a real merge request's metadata, or a
    synthesized equivalent for a local diff (see `_local_meta`).
    """
    changed = [c.get("new_path") or c.get("old_path") for c in changes.get("changes", [])]
    counter = TokenCounter()
    budget = settings.llm.context_budget_tokens
    affordances = _affordance_context(settings, persona, repo, meta, changed, counter, budget)
    diff_text = _budgeted_diff(changes, counter, budget // 2)

    review = _generate_review(
        llm, persona, meta, changed, affordances, diff_text, counter, budget
    )
    ground = _ground(settings, repo, review)
    body = _apply_marking(
        settings.marking.banner,
        review + _grounding_suffix(ground) + _SIGNATURE.format(persona=persona.name)
    )
    return body, changed, ground


def review_merge_request(
    settings: Settings,
    *,
    project: str,
    mr_iid: int,
    repo: str | Path | None = None,
    post: bool = True,
    gitlab: GitLabClient | None = None,
    llm: LLMClient | None = None,
) -> dict[str, Any]:
    """Generate (and optionally post) an initial review for a merge request."""
    from ...netpolicy import enforce
    from ...security import enforce_fips_policy

    enforce_fips_policy(settings.fips.require_fips, settings.fips.allow_non_fips)
    enforce(settings)  # validate LLM + GitLab endpoints (TLS / allow-list)
    persona = load_persona(settings.persona.profile)
    owns_gl = gitlab is None
    owns_llm = llm is None
    gitlab = gitlab or GitLabClient(settings.gitlab)
    llm = llm or LLMClient(settings.llm, leanctx=settings.leanctx)
    try:
        mr = gitlab.get_merge_request(project, mr_iid)
        changes = gitlab.get_merge_request_changes(project, mr_iid)
        body, changed, ground = _review_body(
            settings, persona, meta=mr, changes=changes, repo=repo, llm=llm)

        result: dict[str, Any] = {
            "project": project,
            "mr_iid": mr_iid,
            "title": mr.get("title", ""),
            "changed_files": changed,
            "persona": persona.name,
            "review": body,
            "grounding": ground.to_dict() if ground else None,
            "posted": False,
        }
        if post:
            note = gitlab.create_note(project, mr_iid, body)
            result["posted"] = True
            result["note_id"] = note.get("id")
        get_audit_logger(settings).record(
            "review_mr",
            target={"project": project, "mr_iid": mr_iid,
                    "changed_files": len(changed), "posted": result["posted"]},
            model=settings.llm.model, endpoint=settings.llm.base_url,
        )
        return result
    finally:
        if owns_gl:
            gitlab.close()
        if owns_llm:
            llm.close()


_LOCAL_SCOPE_LABELS = {
    "since_base": "the {base} branch",
    "since_ref": "{base}",
    "working_tree": "HEAD (uncommitted changes)",
    "staged": "HEAD (staged changes)",
    "range": "{base}..{head}",
    "explicit": "an explicit file list",
}


def _local_meta(repo: Path, scope: gitscope.ChangeSet) -> dict[str, Any]:
    """Synthesize the merge-request-shaped metadata `_review_body` expects, from a
    local `gitscope.ChangeSet` — there is no real MR title/description/branches to
    read, so this is what the prompt sees instead."""
    branch = gitscope.current_branch(repo)
    label = _LOCAL_SCOPE_LABELS.get(scope.scope, scope.scope).format(
        base=scope.base_ref, head=scope.head_sha)
    return {
        "title": f"Local changes on {branch}, vs {label}",
        "description": "",
        "source_branch": branch,
        "target_branch": scope.base_ref or "(none)",
    }


def review_local_changes(
    settings: Settings,
    *,
    repo: str | Path,
    scope: gitscope.ChangeSet | None = None,
    base: str | None = None,
    llm: LLMClient | None = None,
) -> dict[str, Any]:
    """Generate a review of the local git delta — no GitLab, nothing posted.

    Reuses the exact same review-generation path `review_merge_request` uses
    (`_review_body`): full-repo affordance grounding (delta-prioritized), a
    diff-budgeted prompt, one LLM call. The only differences are where the change
    list comes from — a local `gitscope.ChangeSet` (default: `gitscope.since_base`,
    i.e. the delta since the auto-detected base branch) instead of the GitLab API —
    and that nothing is posted; the caller (the CLI) prints the result.

    ``scope`` is normally supplied already resolved (the CLI builds it via
    `gitscope.resolve_scope`, honoring `--base`/`--since`/`--staged`/
    `--working-tree`/`--path`); left unset, this resolves `gitscope.since_base`
    itself so a direct Python caller does not have to build one by hand.
    """
    from ...netpolicy import enforce
    from ...security import enforce_fips_policy

    enforce_fips_policy(settings.fips.require_fips, settings.fips.allow_non_fips)
    enforce(settings)  # validate the LLM endpoint (TLS / allow-list)
    persona = load_persona(settings.persona.profile)
    repo_path = Path(repo)
    if scope is None:
        scope = gitscope.since_base(repo_path, base=base)

    owns_llm = llm is None
    llm = llm or LLMClient(settings.llm, leanctx=settings.leanctx)
    try:
        meta = _local_meta(repo_path, scope)
        changes = scope.to_gitlab_style()
        body, changed, ground = _review_body(
            settings, persona, meta=meta, changes=changes, repo=repo_path, llm=llm)

        result: dict[str, Any] = {
            "repo": str(repo_path),
            "scope": scope.summary_dict(),
            "changed_files": changed,
            "persona": persona.name,
            "review": body,
            "grounding": ground.to_dict() if ground else None,
        }
        get_audit_logger(settings).record(
            "review_local",
            target={"repo": str(repo_path), "scope": scope.scope,
                    "changed_files": len(changed)},
            model=settings.llm.model, endpoint=settings.llm.base_url,
        )
        return result
    finally:
        if owns_llm:
            llm.close()


def respond_to_mention(
    settings: Settings,
    *,
    project: str,
    mr_iid: int,
    discussion_id: str,
    thread: str,
    repo: str | Path | None = None,
    post: bool = True,
    gitlab: GitLabClient | None = None,
    llm: LLMClient | None = None,
) -> dict[str, Any]:
    """Reply in-thread to a comment that mentioned the bot."""
    from ...netpolicy import enforce
    from ...security import enforce_fips_policy

    enforce_fips_policy(settings.fips.require_fips, settings.fips.allow_non_fips)
    enforce(settings)
    persona = load_persona(settings.persona.profile)
    owns_gl = gitlab is None
    owns_llm = llm is None
    gitlab = gitlab or GitLabClient(settings.gitlab)
    llm = llm or LLMClient(settings.llm, leanctx=settings.leanctx)
    try:
        mr = gitlab.get_merge_request(project, mr_iid)
        changes = gitlab.get_merge_request_changes(project, mr_iid)
        changed = gitlab.changed_paths(changes)
        counter = TokenCounter()
        budget = settings.llm.context_budget_tokens
        affordances = _affordance_context(
            settings, persona, repo, mr, changed, counter, budget // 2
        )

        sys = harden_system_prompt(
            persona.system_prompt()
            + f"\nYou are replying in a discussion thread. Keep it to at most "
            f"{persona.max_reply_paragraphs} short paragraph(s). Answer the question "
            "directly using the provided context."
        )
        ctx_block = wrap_untrusted(affordances or "(none)", "affordances")
        user = (
            f"Merge request: {mr.get('title','')}\n\n"
            f"Discussion so far:\n{wrap_untrusted(thread, 'mr-comment')}\n\n"
            f"Relevant project context:\n{ctx_block}\n\n"
            "Write your reply:"
        )
        reply = _chat(llm, sys, user, max_tokens=settings.llm.max_output_tokens)
        body = _apply_marking(
            settings.marking.banner, reply + _SIGNATURE.format(persona=persona.name)
        )
        result: dict[str, Any] = {
            "project": project, "mr_iid": mr_iid, "discussion_id": discussion_id,
            "persona": persona.name, "reply": body, "posted": False,
        }
        if post:
            note = gitlab.reply_to_discussion(project, mr_iid, discussion_id, body)
            result["posted"] = True
            result["note_id"] = note.get("id")
        get_audit_logger(settings).record(
            "review_reply",
            target={"project": project, "mr_iid": mr_iid,
                    "discussion_id": discussion_id, "posted": result["posted"]},
            model=settings.llm.model, endpoint=settings.llm.base_url,
        )
        return result
    finally:
        if owns_gl:
            gitlab.close()
        if owns_llm:
            llm.close()


def _generate_review(llm, persona, mr, changed, affordances, diff_text, counter, budget) -> str:
    sys = harden_system_prompt(persona.system_prompt())
    description = (mr.get("description") or "").strip()[:1000]
    user = (
        f"# Merge request to review\n"
        f"Title: {wrap_untrusted(mr.get('title', ''), 'mr-title')}\n"
        f"Description:\n{wrap_untrusted(description, 'mr-description')}\n"
        f"Source -> target: {mr.get('source_branch','?')} -> {mr.get('target_branch','?')}\n"
        f"Changed files ({len(changed)}): {', '.join(changed[:40])}\n\n"
        f"## Project context (from secagent affordances)\n"
        f"{wrap_untrusted(affordances or '(none available)', 'affordances')}\n\n"
        f"## Diff\n{wrap_untrusted(diff_text, 'diff')}\n\n"
        "Write the review now. Structure it as: a one-line summary, then a short list of "
        "the most important findings (each with file references), then optional minor notes."
    )
    # No local cap — see file_summary: a tight cap costs a wasted call plus a
    # retry on every request against a reasoning model.
    return _chat(llm, sys, user)


def _chat(llm: LLMClient, system: str, user: str, *,
          max_tokens: int | None = None) -> str:
    """``max_tokens=None`` uses the client budget, which is sized to the model."""
    try:
        resp = llm.chat(
            [{"role": "system", "content": system}, {"role": "user", "content": user}],
            max_tokens=max_tokens,
        )
        return resp.content.strip() or "_(the model returned no content)_"
    except Exception as exc:  # surface as a comment rather than crashing the webhook
        # The return value is posted publicly, under the bot identity, on someone else's
        # merge request. `httpx.HTTPStatusError.__str__` embeds the full request URL, so
        # returning `str(exc)` published the model endpoint's host and port to whoever
        # could read the MR. Name the failure — silence here would read as a clean
        # review — but keep the detail in the operator's log, where it belongs.
        log.warning("review generation failed: %s", exc, exc_info=True)
        return (f"_secagent could not generate a review: the model endpoint failed "
                f"({type(exc).__name__}). Details are in the secagent server log. "
                f"**This comment is not a review — nothing was checked.**_")


def _ground(settings: Settings, repo: str | Path | None,
            review: str) -> grounding.Grounding | None:
    """Check the prose we are about to publish against the index that knows the truth.

    The triage path — whose output nobody reads publicly — has grounded its claims since
    the grounding module was added. The reviewer, which posts prose on someone else's
    merge request, never called it: zero references in the whole review agent. That is
    backwards on risk, and the infrastructure to catch a cited file or symbol that does
    not exist was already sitting in the codebase.

    Returns ``None`` when there is no index to check against, which is not the same as
    "checked and clean" — the caller must not present it as such.
    """
    if not repo:
        return None
    repo_path = Path(repo)
    if not repo_path.is_dir():
        return None
    store = AffordanceStore(repo_path, settings.affordances.store_dir)
    try:
        if store.load_project_map() is None:
            return None
        return grounding.check(store, review)
    except Exception as exc:  # noqa: BLE001 - a failed check must not block the review
        # Best-effort, but never invisible: a grounding pass that fails quietly is
        # indistinguishable from one that found nothing to flag.
        log.warning("grounding check failed; the review is posted unchecked: %s", exc)
        return None
    finally:
        store.close()


def _grounding_suffix(ground: grounding.Grounding | None) -> str:
    """Annotate the review; never edit it.

    Dropping or rewriting a finding the index cannot confirm would turn a checkable wrong
    claim into an invisible missing one. The reader gets the model's words verbatim plus
    a line saying which of its references resolve.
    """
    if ground is None or ground.ok:
        return ""
    return f"\n\n---\n*secagent grounding: {ground.note()}*"


def _affordance_context(
    settings: Settings,
    persona: Persona,
    repo: str | Path | None,
    mr: dict[str, Any],
    changed: list[str],
    counter: TokenCounter,
    budget: int,
) -> str:
    if not persona.use_affordances or not repo:
        return ""
    repo_path = Path(repo)
    if not repo_path.is_dir():
        return ""
    store = AffordanceStore(repo_path, settings.affordances.store_dir)
    try:
        if store.load_project_map() is None:
            # Build a lightweight (heuristic-only) store so the reviewer has structure.
            store.close()
            light = settings.model_copy(deep=True)
            light.affordances.llm_summaries = False
            index_repo(repo_path, light)
            store = AffordanceStore(repo_path, settings.affordances.store_dir)
        builder = ContextBuilder(store, budget, counter)
        query = mr.get("title", "") + " " + " ".join(Path(p).name for p in changed)
        return builder.for_query(query, extra_paths=changed)
    finally:
        store.close()


def _budgeted_diff(changes: dict[str, Any], counter: TokenCounter, budget: int) -> str:
    """Concatenate per-file diffs, truncating to fit the token budget."""
    parts: list[str] = []
    used = 0
    for c in changes.get("changes", []):
        path = c.get("new_path") or c.get("old_path") or "?"
        diff = c.get("diff", "")
        header = f"\n### {path}\n"
        block = header + "```diff\n" + diff + "\n```\n"
        tokens = counter.count(block)
        if used + tokens > budget:
            remaining = budget - used
            if remaining > 80:
                clipped = _truncate_diff(diff, counter, remaining)
                parts.append(header + "```diff\n" + clipped + "\n```")
            parts.append("\n_(remaining diffs omitted to fit context budget)_")
            break
        parts.append(block)
        used += tokens
    return "".join(parts) if parts else "(no textual diff)"


def _truncate_diff(diff: str, counter: TokenCounter, budget: int) -> str:
    lines = diff.splitlines()
    out: list[str] = []
    used = 0
    for line in lines:
        t = counter.count(line) + 1
        if used + t > budget:
            out.append("... (truncated)")
            break
        out.append(line)
        used += t
    return "\n".join(out)
