"""``secagent init`` — one-time per-developer onboarding.

Wires up TWO consumers of the same per-user identity (``secagent login`` /
``secagent token --user`` — see ``secsso.py``) so a developer can point both pi and
secagent's own CLI at a SecRouter deployment, authenticated as themselves:

* ``~/.pi/agent/models.json`` — registers a ``secrouter`` pi provider whose
  ``apiKey`` runs ``!secagent token --user``. This is the DEFAULT onboarding path and
  deliberately does not depend on ``pi/extensions/secrouter-auth.ts`` (a separate,
  still-valid, pi-native device-code extension) — see that file's own header for the
  alternative it offers.
* ``~/.secagent/config.yaml`` — a per-user layer ``config.py``'s ``load_settings``
  auto-loads (see there), so the CLI's own use cases (``index``/``scan``/``docs
  build``/...) also run against SecRouter as the developer, with no env vars to
  export by hand.

Both files are safe to regenerate: ``run_init`` only ever touches the ``secrouter``
key of ``models.json`` and the ``llm``/``secsso`` sections of ``config.yaml``, so
anything else a developer adds to either file by hand (another pi provider, another
secagent config section) survives a re-run. ``--force`` additionally backs up the
pre-existing file before writing — see ``_backup``.

URL derivation (``derive_peers``) MUST match what secdeploy would derive for the same
domain (``secdeploy/src/secdeploy/topology.py`` ``Topology.env_for`` /
``wiring.secrouter_oidc_config``) and what SecSSO's own bootstrap script prints
(``secsso/bootstrap/secsso.sh`` ``secagent-config``) — verified against both, not
invented; see the module-level constants below and this module's tests.
"""

from __future__ import annotations

import json
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

# ── Suite URL conventions ────────────────────────────────────────────────────────
#
# secrouter.<domain>:47002  and  secsso.<domain>:9000  are this suite's fixed peer
# ports (matches secdeploy's topology port assignments and secsso/.env.example's
# SECSSO_HTTP_PORT default). SecSSO's device/token paths are Authentik's fixed OAuth2
# endpoint paths (`/application/o/device/`, `/application/o/token/`; confirmed against
# secsso/bootstrap/secsso.sh and secsso/blueprints/secagent-pi.yaml), shared by every
# OAuth2 client on the instance — not per-client, so no separate "device provider"
# base is needed.
_SECROUTER_PORT = 47002
_SECSSO_PORT = 9000
_DEVICE_CLIENT_ID = "secagent-pi"
_DEVICE_SCOPE = "openid profile email secrouter"
_DEFAULT_MODEL = "balanced"

# KIMI GUARD (+ PRC-jurisdiction models generally): `--model` must never register a
# model from an excluded family under the generated `secrouter` provider. See the
# user's `secrouter-model-origin` policy (curate US-origin open-weight defaults,
# exclude PRC-jurisdiction models). This is a code-level guard, not just a comment —
# `_check_model_origin` actually refuses the name below.
_BLOCKED_MODEL_SUBSTRINGS = ("kimi", "moonshot", "qwen", "deepseek", "glm")

_MODELS_JSON_COMMENT = [
    "Generated by `secagent init` -- registers ONLY the 'secrouter' provider so pi",
    "talks to SecRouter as YOU, the developer.",
    "",
    "Auth: apiKey runs `secagent token --user`, which prints your own cached SecSSO",
    "device-code token (see `secagent login`) -- refreshed automatically, nothing",
    "here is a stored credential. Re-run `secagent login` once it expires with no",
    "refresh token left to renew from.",
    "",
    "Re-run `secagent init --domain <domain>` any time to update baseUrl/model; it",
    "only ever touches this 'secrouter' key, so any other provider you add by hand",
    "is left alone.",
    "",
    "KIMI GUARD: this file registers ONLY the 'secrouter' provider. It does not",
    "enable, override, or reference pi's built-in 'Kimi For Coding' provider (PRC",
    "jurisdiction -- excluded from this suite's model defaults).",
]


class OnboardingError(RuntimeError):
    """`secagent init` could not proceed: bad/insufficient arguments, an excluded
    model, or an existing file it could not safely merge into (see `--force`)."""


@dataclass(frozen=True)
class SuitePeers:
    """The three URLs `secagent init` needs — derived from `--domain`, or supplied
    directly via `--secrouter-url`/`--secsso-url`."""

    secrouter_url: str              # e.g. https://secrouter.<domain>:47002/v1
    device_authorization_url: str   # e.g. https://secsso.<domain>:9000/application/o/device/
    token_url: str                  # e.g. https://secsso.<domain>:9000/application/o/token/


def default_models_json_path() -> Path:
    """``~/.pi/agent/models.json`` — a function (not a module constant) so it re-reads
    ``$HOME`` on every call; see ``config.py``'s ``_user_config_path`` for why that
    matters under test."""
    return Path("~/.pi/agent/models.json").expanduser()


def default_user_config_path() -> Path:
    """``~/.secagent/config.yaml`` — see ``default_models_json_path``'s docstring."""
    return Path("~/.secagent/config.yaml").expanduser()


def _peers_from_secsso_base(base: str) -> tuple[str, str]:
    base = base.rstrip("/")
    return f"{base}/application/o/device/", f"{base}/application/o/token/"


def derive_peers(domain: str) -> SuitePeers:
    """Suite-convention peer URLs for a bare domain, e.g. ``example.internal`` ->

      secrouter:  https://secrouter.example.internal:47002/v1
      secsso:     https://secsso.example.internal:9000/application/o/device/  (device auth)
                  https://secsso.example.internal:9000/application/o/token/   (token)
    """
    secsso_base = f"https://secsso.{domain}:{_SECSSO_PORT}"
    device_url, token_url = _peers_from_secsso_base(secsso_base)
    return SuitePeers(
        secrouter_url=f"https://secrouter.{domain}:{_SECROUTER_PORT}/v1",
        device_authorization_url=device_url,
        token_url=token_url,
    )


def resolve_peers(
    *, domain: str | None, secrouter_url: str | None, secsso_url: str | None,
) -> SuitePeers:
    """Combine ``--domain`` derivation (:func:`derive_peers`) with explicit
    ``--secrouter-url``/``--secsso-url`` overrides.

    Either override may be given independently of the other and independently of
    ``--domain`` — e.g. ``--domain <domain> --secrouter-url <custom>`` keeps SecSSO
    domain-derived and only overrides SecRouter. At least one full source (a domain,
    or both explicit URLs) is required; raises :class:`OnboardingError` otherwise.
    ``--secrouter-url`` is used verbatim as the LLM base URL (include the trailing
    ``/v1``); ``--secsso-url`` is a bare base (no path) that the well-known Authentik
    device/token paths are appended to, exactly like the domain-derived case.
    """
    if not domain and not (secrouter_url and secsso_url):
        raise OnboardingError(
            "pass --domain <suite-domain>, or both --secrouter-url and --secsso-url "
            "(secagent init needs to know where SecRouter and SecSSO are)"
        )
    base = derive_peers(domain) if domain else None

    if secrouter_url:
        final_secrouter_url = secrouter_url
    elif base is not None:
        final_secrouter_url = base.secrouter_url
    else:  # pragma: no cover - unreachable: the guard above requires one or the other
        raise OnboardingError("--secrouter-url is required without --domain")

    if secsso_url:
        device_url, token_url = _peers_from_secsso_base(secsso_url)
    elif base is not None:
        device_url, token_url = base.device_authorization_url, base.token_url
    else:  # pragma: no cover - unreachable: the guard above requires one or the other
        raise OnboardingError("--secsso-url is required without --domain")

    return SuitePeers(final_secrouter_url, device_url, token_url)


def _check_model_origin(model: str) -> None:
    lowered = model.lower()
    for bad in _BLOCKED_MODEL_SUBSTRINGS:
        if bad in lowered:
            raise OnboardingError(
                f"refusing to register model {model!r}: matches an excluded "
                f"PRC-jurisdiction model family ({bad!r}). Choose a SecRouter-exposed "
                "US-origin model or tier instead."
            )


def _secrouter_provider(secrouter_url: str, model: str) -> dict[str, Any]:
    return {
        "api": "openai-completions",
        "baseUrl": secrouter_url,
        "apiKey": "!secagent token --user",
        "models": [{"id": model, "name": f"{model} (SecRouter)"}],
    }


# ── file I/O: load / merge / backup / atomic-write, shared shape for both files ────


def _load_existing_json(path: Path) -> tuple[dict[str, Any] | None, bool]:
    """Return ``(data, ok)``. ``ok=False`` means the file exists but is not a JSON
    object secagent init can safely merge into."""
    if not path.exists():
        return None, True
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None, False
    return (data, True) if isinstance(data, dict) else (None, False)


def _load_existing_yaml(path: Path) -> tuple[dict[str, Any] | None, bool]:
    if not path.exists():
        return None, True
    try:
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
    except (OSError, yaml.YAMLError):
        return None, False
    if data is None:
        return {}, True
    return (data, True) if isinstance(data, dict) else (None, False)


def _backup(path: Path) -> Path | None:
    """Copy ``path`` to a timestamped ``.bak-<UTC timestamp>`` sibling. ``None`` (no
    backup made) when there was nothing there to back up."""
    if not path.exists():
        return None
    stamp = time.strftime("%Y%m%dT%H%M%SZ", time.gmtime())
    backup_path = path.with_name(f"{path.name}.bak-{stamp}")
    backup_path.write_bytes(path.read_bytes())
    return backup_path


def _atomic_write_text(path: Path, text: str) -> None:
    """Write-then-rename so a crash mid-write never leaves a truncated file behind —
    same crash-safety reasoning as ``secsso.py``'s cache writes."""
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(text, encoding="utf-8")
    tmp.replace(path)


def _merged_models_json(
    existing: dict[str, Any] | None, provider: dict[str, Any],
) -> dict[str, Any]:
    result = dict(existing) if existing else {}
    providers = dict(result.get("providers") or {})
    providers["secrouter"] = provider
    result["providers"] = providers
    # Always refresh the guidance/KIMI-guard comment to the current one, even when
    # merging into a file `secagent init` wrote before — it is generated scaffolding,
    # not user data, so keeping it current is the right call on every re-run.
    result["_comment"] = list(_MODELS_JSON_COMMENT)
    return result


def _write_models_json(path: Path, peers: SuitePeers, model: str, force: bool) -> Path | None:
    existing, ok = _load_existing_json(path)
    if not ok and not force:
        raise OnboardingError(
            f"{path} exists but is not valid JSON -- re-run `secagent init --force` "
            "to back it up and replace it, or fix/remove it by hand first"
        )
    backup = _backup(path) if force else None
    if not ok:
        existing = None  # --force with unparseable content: start clean, don't merge garbage
    data = _merged_models_json(existing, _secrouter_provider(peers.secrouter_url, model))
    path.parent.mkdir(parents=True, exist_ok=True)
    _atomic_write_text(path, json.dumps(data, indent=2) + "\n")
    return backup


def _user_config_yaml(
    peers: SuitePeers, model: str, domain: str | None, extra_sections: dict[str, Any],
) -> str:
    header = (
        "# Generated by `secagent init"
        + (f" --domain {domain}" if domain else "")
        + "` -- your OWN per-user config.\n"
        "# Auto-loaded from ~/.secagent/config.yaml: built-in defaults < this file <\n"
        "# --config/SECAGENT_CONFIG < SECAGENT_* env vars (see docs/configuration.md).\n"
        "# Re-run `secagent init` any time to update -- it only touches the `llm` and\n"
        "# `secsso` sections below; anything else you add here by hand is left alone.\n"
        "#\n"
        "# Nothing below is a secret: llm.api_key runs `secagent token --user`, which\n"
        "# prints YOUR OWN cached SecSSO token (see `secagent login`) fresh on every\n"
        "# request -- no credential is ever written to this file.\n"
    )
    body: dict[str, Any] = dict(extra_sections)
    body["llm"] = {
        "base_url": peers.secrouter_url,
        "api_key": "!secagent token --user",
        "model": model,
    }
    body["secsso"] = {
        "device_authorization_url": peers.device_authorization_url,
        "token_url": peers.token_url,
        "device_client_id": _DEVICE_CLIENT_ID,
        "device_scope": _DEVICE_SCOPE,
    }
    return header + "\n" + yaml.safe_dump(body, sort_keys=False, default_flow_style=False)


def _write_user_config(
    path: Path, peers: SuitePeers, model: str, domain: str | None, force: bool,
) -> Path | None:
    existing, ok = _load_existing_yaml(path)
    if not ok and not force:
        raise OnboardingError(
            f"{path} exists but is not valid YAML -- re-run `secagent init --force` "
            "to back it up and replace it, or fix/remove it by hand first"
        )
    backup = _backup(path) if force else None
    if not ok:
        existing = None
    extra_sections = {k: v for k, v in (existing or {}).items() if k not in ("llm", "secsso")}
    text = _user_config_yaml(peers, model, domain, extra_sections)
    path.parent.mkdir(parents=True, exist_ok=True)
    _atomic_write_text(path, text)
    return backup


@dataclass
class InitResult:
    models_json_path: Path
    config_path: Path
    models_json_backup: Path | None
    config_backup: Path | None
    peers: SuitePeers
    model: str

    def summary_lines(self) -> list[str]:
        """Human-readable "exactly what was written" report for the CLI."""
        lines: list[str] = []
        if self.models_json_backup:
            lines.append(f"Backed up previous models.json -> {self.models_json_backup}")
        lines.append(
            f"Wrote {self.models_json_path} "
            f"(secrouter provider: baseUrl={self.peers.secrouter_url}, model={self.model})"
        )
        if self.config_backup:
            lines.append(f"Backed up previous config.yaml -> {self.config_backup}")
        lines.append(f"Wrote {self.config_path} (llm + secsso sections)")
        lines.append("")
        lines.append("Next: run `secagent login` to authenticate as yourself.")
        return lines


def run_init(
    *,
    domain: str | None = None,
    secrouter_url: str | None = None,
    secsso_url: str | None = None,
    model: str = _DEFAULT_MODEL,
    force: bool = False,
    models_json_path: Path | None = None,
    config_path: Path | None = None,
) -> InitResult:
    """Implements ``secagent init``.

    ``models_json_path``/``config_path`` are overridable only for tests; real callers
    always target the fixed per-user defaults (:func:`default_models_json_path` /
    :func:`default_user_config_path`) — these are dotfile locations, not
    settings-driven, so there is no config flag for them.
    """
    _check_model_origin(model)
    peers = resolve_peers(domain=domain, secrouter_url=secrouter_url, secsso_url=secsso_url)

    models_path = models_json_path or default_models_json_path()
    cfg_path = config_path or default_user_config_path()

    models_backup = _write_models_json(models_path, peers, model, force)
    config_backup = _write_user_config(cfg_path, peers, model, domain, force)

    return InitResult(
        models_json_path=models_path,
        config_path=cfg_path,
        models_json_backup=models_backup,
        config_backup=config_backup,
        peers=peers,
        model=model,
    )
