"""C/C++ AST extraction via libclang.

When libclang is available this produces *accurate* function definitions and call
sites — the foundation for per-function documentation and the inter-file call map.
A ``compile_commands.json`` (discovered, or generated by the agent with e.g.
``cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON`` / ``bear -- make``) gives the best
results; without one we parse best-effort with ``-ferror-limit=0`` and auto-discovered
include directories — clang is error-tolerant and still recovers the functions and
call names in a file (see docs/field notes).

Everything degrades gracefully: if libclang is not installed, or a translation unit
cannot be created, the caller falls back to the regex symbol path and/or the LLM.
"""

from __future__ import annotations

import json
import re
import shlex
from dataclasses import asdict, dataclass, field
from functools import lru_cache
from pathlib import Path

# C/C++ source extensions clang should drive (headers are parsed transitively).
CLANG_SOURCE_EXTS = {".c", ".cc", ".cpp", ".cxx", ".c++", ".m", ".mm"}
CLANG_LANGS = {"C", "C++", "Objective-C"}


@dataclass
class FuncDef:
    name: str
    signature: str
    file: str  # repo-relative POSIX
    line: int


@dataclass
class CallSite:
    caller: str  # enclosing function name ("" at file scope)
    callee: str  # called function name
    file: str
    line: int


@dataclass
class ParsedUnit:
    functions: list[FuncDef] = field(default_factory=list)
    calls: list[CallSite] = field(default_factory=list)
    parsed: bool = False  # False = libclang missing or TU could not be created
    errors: int = 0
    # Headers clang could not find. These are what actually degrade the result: types
    # collapse to implicit `int` and calls into the unresolved declarations vanish.
    missing_headers: list[str] = field(default_factory=list)

    @property
    def degraded(self) -> bool:
        """True when the parse lost fidelity in a way that affects RESULTS.

        Only *project* headers count. A missing C standard-library header is near
        universal — a pip-installed libclang ships no libc headers, so `stdint.h` is
        unresolved on most hosts — yet clang still recovers the full call graph and
        correct signatures from it. Verified on cFS: with only stdint/stdbool/stdio
        missing the call map was complete (144 edges) and every signature correct,
        while a missing *project* header (`default_fm_tblstruct.h`) coincided with the
        map collapsing to 34 edges. Counting system headers would make this warn on
        every healthy parse, and a warning that always fires is one nobody reads.
        """
        return bool(self.missing_project_headers)

    @property
    def missing_project_headers(self) -> list[str]:
        """Missing headers that are the project's own, not the C/C++ standard library."""
        return [h for h in self.missing_headers if not is_system_header(h)]


# Bump when the parser/extraction changes, to invalidate cached AST results.
# v2: ParsedUnit gained missing_headers (fidelity reporting).
CLANG_PARSE_VERSION = "clang-v2"

_MISSING_HEADER_RE = re.compile(r"'([^']+)' file not found")

# C/C++ standard-library headers. Absent from a pip-installed libclang on most hosts, and
# their absence does NOT meaningfully degrade symbol/call extraction (clang recovers).
_STD_HEADERS = frozenset({
    "assert.h", "complex.h", "ctype.h", "errno.h", "fenv.h", "float.h", "inttypes.h",
    "iso646.h", "limits.h", "locale.h", "math.h", "setjmp.h", "signal.h", "stdalign.h",
    "stdarg.h", "stdatomic.h", "stdbool.h", "stddef.h", "stdint.h", "stdio.h",
    "stdlib.h", "stdnoreturn.h", "string.h", "tgmath.h", "threads.h", "time.h",
    "uchar.h", "wchar.h", "wctype.h",
})


def is_system_header(name: str) -> bool:
    """True for a C/C++ standard-library header (bare name, or any <...> C++ header)."""
    base = name.rsplit("/", 1)[-1]
    if base in _STD_HEADERS:
        return True
    # C++ standard headers carry no extension (<vector>, <string>, <memory>).
    return "/" not in name and "." not in name


def unit_to_cache(unit: ParsedUnit) -> dict:
    """Serialize a parsed unit for the content cache (only parsed units are cached)."""
    return {
        "functions": [asdict(f) for f in unit.functions],
        "calls": [asdict(c) for c in unit.calls],
        "errors": unit.errors,
        "missing_headers": list(unit.missing_headers),
    }


def unit_from_cache(d: dict) -> ParsedUnit:
    """Reconstruct a parsed unit from its cached form (parsed=True by construction)."""
    return ParsedUnit(
        functions=[FuncDef(**f) for f in d.get("functions", [])],
        calls=[CallSite(**c) for c in d.get("calls", [])],
        parsed=True,
        errors=int(d.get("errors", 0)),
        missing_headers=list(d.get("missing_headers", [])),
    )


@lru_cache(maxsize=1)
def clang_available() -> bool:
    """True if libclang can be imported and a parser index created."""
    try:
        import clang.cindex as cx

        cx.Index.create()
        return True
    except Exception:  # noqa: BLE001 - any import/load failure means "use the fallback"
        return False


def discover_compile_db(repo_root: Path, configured: str = "") -> dict[str, list[str]]:
    """Map absolute source path -> compile args from a ``compile_commands.json``.

    Looks at ``configured`` first, then common build locations. Returns ``{}`` when no
    database is found (callers then use :func:`best_effort_args`).
    """
    candidates: list[Path] = []
    if configured:
        candidates.append(Path(configured))
    candidates += [
        repo_root / "compile_commands.json",
        repo_root / "build" / "compile_commands.json",
        repo_root / "out" / "compile_commands.json",
    ]
    for path in candidates:
        if path and path.is_file():
            try:
                entries = json.loads(path.read_text(encoding="utf-8"))
            except (OSError, json.JSONDecodeError):
                continue
            db: dict[str, list[str]] = {}
            for e in entries:
                src = e.get("file", "")
                if not src:
                    continue
                key = str((Path(e.get("directory", ".")) / src).resolve())
                db[key] = _args_from_entry(e)
            if db:
                return db
    return {}


def _args_from_entry(entry: dict) -> list[str]:
    """Extract compiler flags (-I/-D/-std/...) from a compile_commands entry."""
    if "arguments" in entry:
        tokens = list(entry["arguments"])[1:]  # drop the compiler argv[0]
    else:
        tokens = shlex.split(entry.get("command", ""))[1:]
    keep: list[str] = []
    skip_next = False
    for i, tok in enumerate(tokens):
        if skip_next:
            skip_next = False
            continue
        if tok in ("-o", "-c", "-MF", "-MT"):
            skip_next = tok in ("-o", "-MF", "-MT")
            continue
        if tok.startswith(("-I", "-D", "-std", "-isystem", "-include", "-U", "-f")):
            keep.append(tok)
            if tok in ("-isystem", "-include") and i + 1 < len(tokens):
                keep.append(tokens[i + 1])
                skip_next = True
    return keep


def _include_root(repo_root: Path) -> Path:
    """The outermost ancestor that looks like the project root (has a ``.git``).

    A component-scoped index (e.g. ``apps/fm``) needs the *whole* project's headers to
    resolve cross-component includes (cFS core ``cfe.h`` etc.). Climb past submodule
    ``.git`` pointers to the superproject so include discovery sees them.
    """
    root = repo_root
    p = repo_root
    for _ in range(12):
        if (p / ".git").exists():
            root = p  # keep the OUTERMOST .git (the superproject, not a submodule)
        if p.parent == p:
            break
        p = p.parent
    return root


@lru_cache(maxsize=64)
def best_effort_args(
    repo_root: str, extra: tuple[str, ...] = (), limit: int = 4000
) -> tuple[str, ...]:
    """Include flags for parsing without a compile DB: every project header directory.

    Discovers headers from the project root (so component-scoped indexing still
    resolves cross-component includes) plus any configured ``extra`` dirs.
    ``-ferror-limit=0`` keeps clang recovering past the inevitable missing-header errors.
    """
    dirs: set[str] = set()
    for h in _include_root(Path(repo_root)).rglob("*.h"):
        dirs.add(str(h.parent))
        if len(dirs) >= limit:
            break
    args = ["-ferror-limit=0", "-w"]
    args += [f"-I{d}" for d in sorted(dirs)]
    args += [f"-I{e}" for e in extra]
    return tuple(args)


@lru_cache(maxsize=1)
def system_include_args() -> tuple[str, ...]:
    """Flags so clang can find the C/C++ STANDARD headers.

    A pip-installed libclang ships no libc/libc++ headers, so `<stdint.h>` / `<cstdint>`
    go unresolved — and every unknown type silently collapses to implicit `int`. That
    turns `uint32_t calculateCRC32(uint32_t, uint8_t *, uint32_t)` into
    `int calculateCRC32(int, int *, int)`, which a model will then repeat as fact.
    It does not break the call map (calls resolve by name), which is why the missing
    header is correctly NOT treated as a degraded parse — but it does wreck signatures.

    Discovered once per process; an absent SDK just yields no flags.
    """
    import platform
    import shutil
    import subprocess

    if platform.system() == "Darwin" and shutil.which("xcrun"):
        try:
            r = subprocess.run(["xcrun", "--show-sdk-path"], capture_output=True,
                               text=True, timeout=15)
            sdk = r.stdout.strip()
            if r.returncode == 0 and sdk and Path(sdk).is_dir():
                # -isysroot gives clang both usr/include and the libc++ headers.
                return ("-isysroot", sdk)
        except (OSError, subprocess.SubprocessError):
            pass
    args: list[str] = []
    for d in ("/usr/include", "/usr/local/include"):
        if Path(d).is_dir():
            args += ["-isystem", d]
    return tuple(args)


def parse_file(
    abs_path: Path,
    repo_root: Path,
    compile_db: dict[str, list[str]] | None = None,
    extra_includes: tuple[str, ...] = (),
) -> ParsedUnit:
    """Parse one C/C++ file and return its function definitions and call sites."""
    if not clang_available():
        return ParsedUnit(parsed=False)
    import clang.cindex as cx

    key = str(abs_path.resolve())
    args = (compile_db or {}).get(key)
    if args is None:
        args = list(best_effort_args(str(repo_root), tuple(extra_includes)))
    else:
        args = list(args)
    # Standard-library headers, unless the compile DB already points at a sysroot. A DB
    # produced inside a container names paths that do not exist on this host, so its
    # entries alone are not enough.
    if not any(a.startswith("-isysroot") or a == "-isysroot" for a in args):
        args += list(system_include_args())

    try:
        index = cx.Index.create()
        tu = index.parse(str(abs_path), args=args)
    except Exception:  # noqa: BLE001 - libclang can raise on malformed input
        return ParsedUnit(parsed=False)

    unit = ParsedUnit(parsed=True)
    unit.errors = sum(
        1 for d in tu.diagnostics if d.severity >= cx.Diagnostic.Error
    )
    # A missing header is the specific diagnostic that degrades results: clang keeps
    # going, but unresolved types collapse to implicit `int` and calls into the
    # unparsed declarations are lost — silently. Capture it precisely, because a bare
    # `errors > 0` is a noisy proxy (a file can carry an unrelated error and still
    # produce perfect types).
    unit.missing_headers = sorted({
        m.group(1)
        for d in tu.diagnostics
        if d.severity >= cx.Diagnostic.Error
        and (m := _MISSING_HEADER_RE.search(str(d.spelling)))
    })
    target = str(abs_path)

    def rel(cursor) -> str:
        f = cursor.location.file
        try:
            return Path(f.name).resolve().relative_to(repo_root.resolve()).as_posix()
        except (ValueError, AttributeError):
            return Path(f.name).as_posix() if f else ""

    def visit(cursor, enclosing: str, depth: int) -> None:
        if depth > 200:  # guard against pathological nesting
            return
        for child in cursor.get_children():
            cf = child.location.file
            in_target = cf is not None and cf.name == target
            if child.kind in _CALLABLE_KINDS(cx) and child.is_definition():
                # A C++ method's spelling is the bare method name; qualify it with its
                # class so `Foo::run` and `Bar::run` are distinguishable and the call map
                # can resolve them separately.
                name = _qualified_name(child, cx)
                if in_target:
                    unit.functions.append(
                        FuncDef(name, _signature(child, cx), rel(child),
                                child.location.line)
                    )
                visit(child, name, depth + 1)
            elif child.kind == cx.CursorKind.CALL_EXPR:
                if in_target and child.spelling:
                    # Qualify the callee the same way definitions are, or a call to
                    # `UnicoreParser::reset` (recorded bare as "reset") would never match
                    # its own definition and every method edge would be lost.
                    callee = child.spelling
                    ref = child.referenced
                    if ref is not None:
                        callee = _qualified_name(ref, cx) or callee
                    unit.calls.append(
                        CallSite(enclosing, callee, rel(child), child.location.line)
                    )
                visit(child, enclosing, depth + 1)
            else:
                visit(child, enclosing, depth + 1)

    visit(tu.cursor, "", 0)
    return unit


def _CALLABLE_KINDS(cx) -> frozenset:
    """Cursor kinds that define something callable.

    FUNCTION_DECL alone covers C. In C++ the methods — which are most of the code — are
    CXX_METHOD/CONSTRUCTOR/DESTRUCTOR, so a C++ codebase indexed with only FUNCTION_DECL
    yields almost nothing: 12 functions across 11.6k lines on a real driver library, an
    empty `functions` result per file, and a call map with no method calls in it at all.
    """
    kinds = [cx.CursorKind.FUNCTION_DECL, cx.CursorKind.CXX_METHOD,
             cx.CursorKind.CONSTRUCTOR, cx.CursorKind.DESTRUCTOR]
    for extra in ("FUNCTION_TEMPLATE", "CONVERSION_FUNCTION"):
        kind = getattr(cx.CursorKind, extra, None)
        if kind is not None:
            kinds.append(kind)
    return frozenset(kinds)


def _qualified_name(cursor, cx) -> str:
    """``Class::method`` for a C++ member, else the bare name."""
    name = cursor.spelling or ""
    parent = cursor.semantic_parent
    owner_kinds = {cx.CursorKind.CLASS_DECL, cx.CursorKind.STRUCT_DECL,
                   cx.CursorKind.CLASS_TEMPLATE, cx.CursorKind.UNION_DECL}
    if parent is not None and parent.kind in owner_kinds and parent.spelling:
        return f"{parent.spelling}::{name}"
    return name


def _signature(cursor, cx) -> str:
    ret = cursor.result_type.spelling or "void"
    params = []
    for arg in cursor.get_arguments():
        t = arg.type.spelling
        params.append(f"{t} {arg.spelling}".strip() if arg.spelling else t)
    return f"{ret} {cursor.spelling}({', '.join(params)})"
